# Generated by Django 2.2 on 2019-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsCoordinate',
            fields=[
                ('orderId', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('orderId',),
            },
        ),
    ]
