# Generated by Django 2.2 on 2019-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStartEnd',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('time_min_diff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StartPoint',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gpscoordinate',
            options={},
        ),
        migrations.AddField(
            model_name='gpscoordinate',
            name='road',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gpscoordinate',
            name='orderId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
