# Generated by Django 2.2 on 2019-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0002_auto_20190610_0309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpsCoordinate',
        ),
        migrations.RemoveField(
            model_name='orderstartend',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='orderstartend',
            name='lng',
        ),
        migrations.AddField(
            model_name='orderstartend',
            name='end_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderstartend',
            name='end_lng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderstartend',
            name='start_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderstartend',
            name='start_lng',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
