# Generated by Django 2.2 on 2019-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0003_auto_20190610_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsAllPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
