# Generated by Django 2.2 on 2019-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0005_gpsallpoint'),
    ]

    operations = [

        migrations.AddField(
            model_name='endpoint',
            name='business',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='district',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='street',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
